# Generated by Django 4.2.6 on 2023-10-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_one', models.CharField(max_length=255, verbose_name='ID 1 пользователя')),
                ('chat_two', models.CharField(max_length=255, verbose_name='ID 2 пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала чат-сессии')),
            ],
            options={
                'verbose_name': 'Чат-сессии',
                'verbose_name_plural': 'Чат-сессии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chat_false',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_sob', models.CharField(max_length=30, verbose_name='ID собеседника')),
                ('chat_may', models.CharField(max_length=30, verbose_name='ID мой')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время удаления чат-сессии')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, verbose_name='ID пользователя')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=60, verbose_name='Пол')),
                ('time_queued', models.DateTimeField(auto_now_add=True, verbose_name='Время добавление в очередь')),
            ],
            options={
                'verbose_name': 'Пользователи которые ищут собеседника',
                'verbose_name_plural': 'Пользователи которые ищут собеседника',
                'ordering': ['time_queued'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, unique=True, verbose_name='ID пользователя')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=60, verbose_name='Пол')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='@user_name')),
                ('last_visit', models.DateTimeField(auto_now_add=True, verbose_name='Время первого посещения')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего посещения')),
                ('online', models.BooleanField(default=False, verbose_name='Online')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Блокировка')),
            ],
            options={
                'verbose_name': 'Зарегистрированные пользователи',
                'verbose_name_plural': 'Зарегистрированные пользователи',
                'ordering': ['time_update'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='текс ')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Балы пользователей')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Bot_app_Tg.user', verbose_name='Пользователь')),
            ],
        ),
    ]
