# Generated by Django 4.2.6 on 2023-10-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot_app_Tg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='online',
            field=models.BooleanField(default=False, verbose_name='выбрать'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='content',
            field=models.TextField(verbose_name='текст'),
        ),
    ]
