# Generated by Django 4.2.6 on 2023-10-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot_app_Tg', '0002_userprofile_online_alter_userprofile_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='online',
            new_name='publish',
        ),
    ]
