# Generated by Django 4.2.6 on 2023-10-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot_app_Tg', '0003_rename_online_userprofile_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(default='Напишите название статьи', max_length=150, verbose_name='имя статьи'),
        ),
    ]
